FROM golang:1.11.1-alpine as build

RUN apk add --update --no-cache ca-certificates git
RUN adduser -D -g '' appuser
RUN mkdir ${GOPATH}/src/app
WORKDIR ${GOPATH}/src/app
COPY . .

RUN go get 

RUN CGO_ENABLED=0 GOOS=linux GOARCH=arm go build -a -installsuffix cgo -ldflags="-w -s" -o /go/bin/app

FROM scratch
COPY --from=build /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=build /go/bin/app /app
COPY --from=build /etc/passwd /etc/passwd

USER appuser
EXPOSE 8080

ENTRYPOINT ["/app"]
